/*
VNS3 Controller API

Cohesive networks VNS3 provides complete control of your network's addressing, routes, rules and edge enabling a secure, connected and reactive cloud network. 

API version: 5.1.5
Contact: support@cohesive.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// LdapUserSettings struct for LdapUserSettings
type LdapUserSettings struct {
	// Base DN from which to search for Users
	UserBase *string `json:"user_base,omitempty"`
	// Attribute type for the Users
	UserIdAttribute *int32 `json:"user_id_attribute,omitempty"`
	// Search filter for Users
	UserListFilter *string `json:"user_list_filter,omitempty"`
}

// NewLdapUserSettings instantiates a new LdapUserSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLdapUserSettings() *LdapUserSettings {
	this := LdapUserSettings{}
	return &this
}

// NewLdapUserSettingsWithDefaults instantiates a new LdapUserSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLdapUserSettingsWithDefaults() *LdapUserSettings {
	this := LdapUserSettings{}
	return &this
}

// GetUserBase returns the UserBase field value if set, zero value otherwise.
func (o *LdapUserSettings) GetUserBase() string {
	if o == nil || o.UserBase == nil {
		var ret string
		return ret
	}
	return *o.UserBase
}

// GetUserBaseOk returns a tuple with the UserBase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LdapUserSettings) GetUserBaseOk() (*string, bool) {
	if o == nil || o.UserBase == nil {
		return nil, false
	}
	return o.UserBase, true
}

// HasUserBase returns a boolean if a field has been set.
func (o *LdapUserSettings) HasUserBase() bool {
	if o != nil && o.UserBase != nil {
		return true
	}

	return false
}

// SetUserBase gets a reference to the given string and assigns it to the UserBase field.
func (o *LdapUserSettings) SetUserBase(v string) {
	o.UserBase = &v
}

// GetUserIdAttribute returns the UserIdAttribute field value if set, zero value otherwise.
func (o *LdapUserSettings) GetUserIdAttribute() int32 {
	if o == nil || o.UserIdAttribute == nil {
		var ret int32
		return ret
	}
	return *o.UserIdAttribute
}

// GetUserIdAttributeOk returns a tuple with the UserIdAttribute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LdapUserSettings) GetUserIdAttributeOk() (*int32, bool) {
	if o == nil || o.UserIdAttribute == nil {
		return nil, false
	}
	return o.UserIdAttribute, true
}

// HasUserIdAttribute returns a boolean if a field has been set.
func (o *LdapUserSettings) HasUserIdAttribute() bool {
	if o != nil && o.UserIdAttribute != nil {
		return true
	}

	return false
}

// SetUserIdAttribute gets a reference to the given int32 and assigns it to the UserIdAttribute field.
func (o *LdapUserSettings) SetUserIdAttribute(v int32) {
	o.UserIdAttribute = &v
}

// GetUserListFilter returns the UserListFilter field value if set, zero value otherwise.
func (o *LdapUserSettings) GetUserListFilter() string {
	if o == nil || o.UserListFilter == nil {
		var ret string
		return ret
	}
	return *o.UserListFilter
}

// GetUserListFilterOk returns a tuple with the UserListFilter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LdapUserSettings) GetUserListFilterOk() (*string, bool) {
	if o == nil || o.UserListFilter == nil {
		return nil, false
	}
	return o.UserListFilter, true
}

// HasUserListFilter returns a boolean if a field has been set.
func (o *LdapUserSettings) HasUserListFilter() bool {
	if o != nil && o.UserListFilter != nil {
		return true
	}

	return false
}

// SetUserListFilter gets a reference to the given string and assigns it to the UserListFilter field.
func (o *LdapUserSettings) SetUserListFilter(v string) {
	o.UserListFilter = &v
}

func (o LdapUserSettings) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.UserBase != nil {
		toSerialize["user_base"] = o.UserBase
	}
	if o.UserIdAttribute != nil {
		toSerialize["user_id_attribute"] = o.UserIdAttribute
	}
	if o.UserListFilter != nil {
		toSerialize["user_list_filter"] = o.UserListFilter
	}
	return json.Marshal(toSerialize)
}

type NullableLdapUserSettings struct {
	value *LdapUserSettings
	isSet bool
}

func (v NullableLdapUserSettings) Get() *LdapUserSettings {
	return v.value
}

func (v *NullableLdapUserSettings) Set(val *LdapUserSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableLdapUserSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableLdapUserSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLdapUserSettings(val *LdapUserSettings) *NullableLdapUserSettings {
	return &NullableLdapUserSettings{value: val, isSet: true}
}

func (v NullableLdapUserSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLdapUserSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


