/*
VNS3 Controller API

Cohesive networks VNS3 provides complete control of your network's addressing, routes, rules and edge enabling a secure, connected and reactive cloud network. 

API version: 5.1.5
Contact: support@cohesive.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// PostTestLdapVpnSchemaSettingsRequest struct for PostTestLdapVpnSchemaSettingsRequest
type PostTestLdapVpnSchemaSettingsRequest struct {
	// Base DN from which to search for Groups
	VpnGroupBase string `json:"vpn_group_base"`
	// Attribute type for the Groups
	VpnGroupIdAttribute string `json:"vpn_group_id_attribute"`
	// Search filter for Groups
	VpnGroupListFilter *string `json:"vpn_group_list_filter,omitempty"`
	// Attribute used to search for a user within the Group
	VpnGroupMemberAttribute string `json:"vpn_group_member_attribute"`
	// Format of the Group Member attribute
	VpnGroupMemberAttrFormat *string `json:"vpn_group_member_attr_format,omitempty"`
	// Search scope for filter
	VpnGroupSearchScope *string `json:"vpn_group_search_scope,omitempty"`
	// Use Google authenticator (OTP)?
	VpnGroupOtp *bool `json:"vpn_group_otp,omitempty"`
	// Number of records to return. Default = 100
	Limit *int32 `json:"limit,omitempty"`
}

// NewPostTestLdapVpnSchemaSettingsRequest instantiates a new PostTestLdapVpnSchemaSettingsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostTestLdapVpnSchemaSettingsRequest(vpnGroupBase string, vpnGroupIdAttribute string, vpnGroupMemberAttribute string) *PostTestLdapVpnSchemaSettingsRequest {
	this := PostTestLdapVpnSchemaSettingsRequest{}
	this.VpnGroupBase = vpnGroupBase
	this.VpnGroupIdAttribute = vpnGroupIdAttribute
	this.VpnGroupMemberAttribute = vpnGroupMemberAttribute
	var vpnGroupMemberAttrFormat string = "UserDN"
	this.VpnGroupMemberAttrFormat = &vpnGroupMemberAttrFormat
	var vpnGroupSearchScope string = "subtree"
	this.VpnGroupSearchScope = &vpnGroupSearchScope
	var vpnGroupOtp bool = false
	this.VpnGroupOtp = &vpnGroupOtp
	var limit int32 = 100
	this.Limit = &limit
	return &this
}

// NewPostTestLdapVpnSchemaSettingsRequestWithDefaults instantiates a new PostTestLdapVpnSchemaSettingsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostTestLdapVpnSchemaSettingsRequestWithDefaults() *PostTestLdapVpnSchemaSettingsRequest {
	this := PostTestLdapVpnSchemaSettingsRequest{}
	var vpnGroupMemberAttrFormat string = "UserDN"
	this.VpnGroupMemberAttrFormat = &vpnGroupMemberAttrFormat
	var vpnGroupSearchScope string = "subtree"
	this.VpnGroupSearchScope = &vpnGroupSearchScope
	var vpnGroupOtp bool = false
	this.VpnGroupOtp = &vpnGroupOtp
	var limit int32 = 100
	this.Limit = &limit
	return &this
}

// GetVpnGroupBase returns the VpnGroupBase field value
func (o *PostTestLdapVpnSchemaSettingsRequest) GetVpnGroupBase() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VpnGroupBase
}

// GetVpnGroupBaseOk returns a tuple with the VpnGroupBase field value
// and a boolean to check if the value has been set.
func (o *PostTestLdapVpnSchemaSettingsRequest) GetVpnGroupBaseOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VpnGroupBase, true
}

// SetVpnGroupBase sets field value
func (o *PostTestLdapVpnSchemaSettingsRequest) SetVpnGroupBase(v string) {
	o.VpnGroupBase = v
}

// GetVpnGroupIdAttribute returns the VpnGroupIdAttribute field value
func (o *PostTestLdapVpnSchemaSettingsRequest) GetVpnGroupIdAttribute() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VpnGroupIdAttribute
}

// GetVpnGroupIdAttributeOk returns a tuple with the VpnGroupIdAttribute field value
// and a boolean to check if the value has been set.
func (o *PostTestLdapVpnSchemaSettingsRequest) GetVpnGroupIdAttributeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VpnGroupIdAttribute, true
}

// SetVpnGroupIdAttribute sets field value
func (o *PostTestLdapVpnSchemaSettingsRequest) SetVpnGroupIdAttribute(v string) {
	o.VpnGroupIdAttribute = v
}

// GetVpnGroupListFilter returns the VpnGroupListFilter field value if set, zero value otherwise.
func (o *PostTestLdapVpnSchemaSettingsRequest) GetVpnGroupListFilter() string {
	if o == nil || o.VpnGroupListFilter == nil {
		var ret string
		return ret
	}
	return *o.VpnGroupListFilter
}

// GetVpnGroupListFilterOk returns a tuple with the VpnGroupListFilter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostTestLdapVpnSchemaSettingsRequest) GetVpnGroupListFilterOk() (*string, bool) {
	if o == nil || o.VpnGroupListFilter == nil {
		return nil, false
	}
	return o.VpnGroupListFilter, true
}

// HasVpnGroupListFilter returns a boolean if a field has been set.
func (o *PostTestLdapVpnSchemaSettingsRequest) HasVpnGroupListFilter() bool {
	if o != nil && o.VpnGroupListFilter != nil {
		return true
	}

	return false
}

// SetVpnGroupListFilter gets a reference to the given string and assigns it to the VpnGroupListFilter field.
func (o *PostTestLdapVpnSchemaSettingsRequest) SetVpnGroupListFilter(v string) {
	o.VpnGroupListFilter = &v
}

// GetVpnGroupMemberAttribute returns the VpnGroupMemberAttribute field value
func (o *PostTestLdapVpnSchemaSettingsRequest) GetVpnGroupMemberAttribute() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VpnGroupMemberAttribute
}

// GetVpnGroupMemberAttributeOk returns a tuple with the VpnGroupMemberAttribute field value
// and a boolean to check if the value has been set.
func (o *PostTestLdapVpnSchemaSettingsRequest) GetVpnGroupMemberAttributeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VpnGroupMemberAttribute, true
}

// SetVpnGroupMemberAttribute sets field value
func (o *PostTestLdapVpnSchemaSettingsRequest) SetVpnGroupMemberAttribute(v string) {
	o.VpnGroupMemberAttribute = v
}

// GetVpnGroupMemberAttrFormat returns the VpnGroupMemberAttrFormat field value if set, zero value otherwise.
func (o *PostTestLdapVpnSchemaSettingsRequest) GetVpnGroupMemberAttrFormat() string {
	if o == nil || o.VpnGroupMemberAttrFormat == nil {
		var ret string
		return ret
	}
	return *o.VpnGroupMemberAttrFormat
}

// GetVpnGroupMemberAttrFormatOk returns a tuple with the VpnGroupMemberAttrFormat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostTestLdapVpnSchemaSettingsRequest) GetVpnGroupMemberAttrFormatOk() (*string, bool) {
	if o == nil || o.VpnGroupMemberAttrFormat == nil {
		return nil, false
	}
	return o.VpnGroupMemberAttrFormat, true
}

// HasVpnGroupMemberAttrFormat returns a boolean if a field has been set.
func (o *PostTestLdapVpnSchemaSettingsRequest) HasVpnGroupMemberAttrFormat() bool {
	if o != nil && o.VpnGroupMemberAttrFormat != nil {
		return true
	}

	return false
}

// SetVpnGroupMemberAttrFormat gets a reference to the given string and assigns it to the VpnGroupMemberAttrFormat field.
func (o *PostTestLdapVpnSchemaSettingsRequest) SetVpnGroupMemberAttrFormat(v string) {
	o.VpnGroupMemberAttrFormat = &v
}

// GetVpnGroupSearchScope returns the VpnGroupSearchScope field value if set, zero value otherwise.
func (o *PostTestLdapVpnSchemaSettingsRequest) GetVpnGroupSearchScope() string {
	if o == nil || o.VpnGroupSearchScope == nil {
		var ret string
		return ret
	}
	return *o.VpnGroupSearchScope
}

// GetVpnGroupSearchScopeOk returns a tuple with the VpnGroupSearchScope field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostTestLdapVpnSchemaSettingsRequest) GetVpnGroupSearchScopeOk() (*string, bool) {
	if o == nil || o.VpnGroupSearchScope == nil {
		return nil, false
	}
	return o.VpnGroupSearchScope, true
}

// HasVpnGroupSearchScope returns a boolean if a field has been set.
func (o *PostTestLdapVpnSchemaSettingsRequest) HasVpnGroupSearchScope() bool {
	if o != nil && o.VpnGroupSearchScope != nil {
		return true
	}

	return false
}

// SetVpnGroupSearchScope gets a reference to the given string and assigns it to the VpnGroupSearchScope field.
func (o *PostTestLdapVpnSchemaSettingsRequest) SetVpnGroupSearchScope(v string) {
	o.VpnGroupSearchScope = &v
}

// GetVpnGroupOtp returns the VpnGroupOtp field value if set, zero value otherwise.
func (o *PostTestLdapVpnSchemaSettingsRequest) GetVpnGroupOtp() bool {
	if o == nil || o.VpnGroupOtp == nil {
		var ret bool
		return ret
	}
	return *o.VpnGroupOtp
}

// GetVpnGroupOtpOk returns a tuple with the VpnGroupOtp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostTestLdapVpnSchemaSettingsRequest) GetVpnGroupOtpOk() (*bool, bool) {
	if o == nil || o.VpnGroupOtp == nil {
		return nil, false
	}
	return o.VpnGroupOtp, true
}

// HasVpnGroupOtp returns a boolean if a field has been set.
func (o *PostTestLdapVpnSchemaSettingsRequest) HasVpnGroupOtp() bool {
	if o != nil && o.VpnGroupOtp != nil {
		return true
	}

	return false
}

// SetVpnGroupOtp gets a reference to the given bool and assigns it to the VpnGroupOtp field.
func (o *PostTestLdapVpnSchemaSettingsRequest) SetVpnGroupOtp(v bool) {
	o.VpnGroupOtp = &v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *PostTestLdapVpnSchemaSettingsRequest) GetLimit() int32 {
	if o == nil || o.Limit == nil {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostTestLdapVpnSchemaSettingsRequest) GetLimitOk() (*int32, bool) {
	if o == nil || o.Limit == nil {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *PostTestLdapVpnSchemaSettingsRequest) HasLimit() bool {
	if o != nil && o.Limit != nil {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *PostTestLdapVpnSchemaSettingsRequest) SetLimit(v int32) {
	o.Limit = &v
}

func (o PostTestLdapVpnSchemaSettingsRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["vpn_group_base"] = o.VpnGroupBase
	}
	if true {
		toSerialize["vpn_group_id_attribute"] = o.VpnGroupIdAttribute
	}
	if o.VpnGroupListFilter != nil {
		toSerialize["vpn_group_list_filter"] = o.VpnGroupListFilter
	}
	if true {
		toSerialize["vpn_group_member_attribute"] = o.VpnGroupMemberAttribute
	}
	if o.VpnGroupMemberAttrFormat != nil {
		toSerialize["vpn_group_member_attr_format"] = o.VpnGroupMemberAttrFormat
	}
	if o.VpnGroupSearchScope != nil {
		toSerialize["vpn_group_search_scope"] = o.VpnGroupSearchScope
	}
	if o.VpnGroupOtp != nil {
		toSerialize["vpn_group_otp"] = o.VpnGroupOtp
	}
	if o.Limit != nil {
		toSerialize["limit"] = o.Limit
	}
	return json.Marshal(toSerialize)
}

type NullablePostTestLdapVpnSchemaSettingsRequest struct {
	value *PostTestLdapVpnSchemaSettingsRequest
	isSet bool
}

func (v NullablePostTestLdapVpnSchemaSettingsRequest) Get() *PostTestLdapVpnSchemaSettingsRequest {
	return v.value
}

func (v *NullablePostTestLdapVpnSchemaSettingsRequest) Set(val *PostTestLdapVpnSchemaSettingsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePostTestLdapVpnSchemaSettingsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePostTestLdapVpnSchemaSettingsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostTestLdapVpnSchemaSettingsRequest(val *PostTestLdapVpnSchemaSettingsRequest) *NullablePostTestLdapVpnSchemaSettingsRequest {
	return &NullablePostTestLdapVpnSchemaSettingsRequest{value: val, isSet: true}
}

func (v NullablePostTestLdapVpnSchemaSettingsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostTestLdapVpnSchemaSettingsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


