/*
VNS3 Controller API

Cohesive networks VNS3 provides complete control of your network's addressing, routes, rules and edge enabling a secure, connected and reactive cloud network. 

API version: 5.1.5
Contact: support@cohesive.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// LdapGroupSettingsResponse struct for LdapGroupSettingsResponse
type LdapGroupSettingsResponse struct {
	Response *LdapGroupSettings `json:"response,omitempty"`
}

// NewLdapGroupSettingsResponse instantiates a new LdapGroupSettingsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLdapGroupSettingsResponse() *LdapGroupSettingsResponse {
	this := LdapGroupSettingsResponse{}
	return &this
}

// NewLdapGroupSettingsResponseWithDefaults instantiates a new LdapGroupSettingsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLdapGroupSettingsResponseWithDefaults() *LdapGroupSettingsResponse {
	this := LdapGroupSettingsResponse{}
	return &this
}

// GetResponse returns the Response field value if set, zero value otherwise.
func (o *LdapGroupSettingsResponse) GetResponse() LdapGroupSettings {
	if o == nil || o.Response == nil {
		var ret LdapGroupSettings
		return ret
	}
	return *o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LdapGroupSettingsResponse) GetResponseOk() (*LdapGroupSettings, bool) {
	if o == nil || o.Response == nil {
		return nil, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *LdapGroupSettingsResponse) HasResponse() bool {
	if o != nil && o.Response != nil {
		return true
	}

	return false
}

// SetResponse gets a reference to the given LdapGroupSettings and assigns it to the Response field.
func (o *LdapGroupSettingsResponse) SetResponse(v LdapGroupSettings) {
	o.Response = &v
}

func (o LdapGroupSettingsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Response != nil {
		toSerialize["response"] = o.Response
	}
	return json.Marshal(toSerialize)
}

type NullableLdapGroupSettingsResponse struct {
	value *LdapGroupSettingsResponse
	isSet bool
}

func (v NullableLdapGroupSettingsResponse) Get() *LdapGroupSettingsResponse {
	return v.value
}

func (v *NullableLdapGroupSettingsResponse) Set(val *LdapGroupSettingsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableLdapGroupSettingsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableLdapGroupSettingsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLdapGroupSettingsResponse(val *LdapGroupSettingsResponse) *NullableLdapGroupSettingsResponse {
	return &NullableLdapGroupSettingsResponse{value: val, isSet: true}
}

func (v NullableLdapGroupSettingsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLdapGroupSettingsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


