/*
VNS3 Controller API

Cohesive networks VNS3 provides complete control of your network's addressing, routes, rules and edge enabling a secure, connected and reactive cloud network. 

API version: 5.1.5
Contact: support@cohesive.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// FirewallFWSetDeleteRequest struct for FirewallFWSetDeleteRequest
type FirewallFWSetDeleteRequest struct {
	// Chained firewall rules seperated by \"\\n\"
	Rules *string `json:"rules,omitempty"`
	// Name of the FWSet. Must be valid chain that begins with one of the following: NETS_, PORTS_, LIST_. 
	Name *string `json:"name,omitempty"`
}

// NewFirewallFWSetDeleteRequest instantiates a new FirewallFWSetDeleteRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFirewallFWSetDeleteRequest() *FirewallFWSetDeleteRequest {
	this := FirewallFWSetDeleteRequest{}
	return &this
}

// NewFirewallFWSetDeleteRequestWithDefaults instantiates a new FirewallFWSetDeleteRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFirewallFWSetDeleteRequestWithDefaults() *FirewallFWSetDeleteRequest {
	this := FirewallFWSetDeleteRequest{}
	return &this
}

// GetRules returns the Rules field value if set, zero value otherwise.
func (o *FirewallFWSetDeleteRequest) GetRules() string {
	if o == nil || o.Rules == nil {
		var ret string
		return ret
	}
	return *o.Rules
}

// GetRulesOk returns a tuple with the Rules field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FirewallFWSetDeleteRequest) GetRulesOk() (*string, bool) {
	if o == nil || o.Rules == nil {
		return nil, false
	}
	return o.Rules, true
}

// HasRules returns a boolean if a field has been set.
func (o *FirewallFWSetDeleteRequest) HasRules() bool {
	if o != nil && o.Rules != nil {
		return true
	}

	return false
}

// SetRules gets a reference to the given string and assigns it to the Rules field.
func (o *FirewallFWSetDeleteRequest) SetRules(v string) {
	o.Rules = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *FirewallFWSetDeleteRequest) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FirewallFWSetDeleteRequest) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *FirewallFWSetDeleteRequest) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *FirewallFWSetDeleteRequest) SetName(v string) {
	o.Name = &v
}

func (o FirewallFWSetDeleteRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Rules != nil {
		toSerialize["rules"] = o.Rules
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableFirewallFWSetDeleteRequest struct {
	value *FirewallFWSetDeleteRequest
	isSet bool
}

func (v NullableFirewallFWSetDeleteRequest) Get() *FirewallFWSetDeleteRequest {
	return v.value
}

func (v *NullableFirewallFWSetDeleteRequest) Set(val *FirewallFWSetDeleteRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableFirewallFWSetDeleteRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableFirewallFWSetDeleteRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFirewallFWSetDeleteRequest(val *FirewallFWSetDeleteRequest) *NullableFirewallFWSetDeleteRequest {
	return &NullableFirewallFWSetDeleteRequest{value: val, isSet: true}
}

func (v NullableFirewallFWSetDeleteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFirewallFWSetDeleteRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


