/*
VNS3 Controller API

Cohesive networks VNS3 provides complete control of your network's addressing, routes, rules and edge enabling a secure, connected and reactive cloud network. 

API version: 5.1.5
Contact: support@cohesive.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// LdapUserSettingsResponse struct for LdapUserSettingsResponse
type LdapUserSettingsResponse struct {
	Response *LdapUserSettings `json:"response,omitempty"`
}

// NewLdapUserSettingsResponse instantiates a new LdapUserSettingsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLdapUserSettingsResponse() *LdapUserSettingsResponse {
	this := LdapUserSettingsResponse{}
	return &this
}

// NewLdapUserSettingsResponseWithDefaults instantiates a new LdapUserSettingsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLdapUserSettingsResponseWithDefaults() *LdapUserSettingsResponse {
	this := LdapUserSettingsResponse{}
	return &this
}

// GetResponse returns the Response field value if set, zero value otherwise.
func (o *LdapUserSettingsResponse) GetResponse() LdapUserSettings {
	if o == nil || o.Response == nil {
		var ret LdapUserSettings
		return ret
	}
	return *o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LdapUserSettingsResponse) GetResponseOk() (*LdapUserSettings, bool) {
	if o == nil || o.Response == nil {
		return nil, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *LdapUserSettingsResponse) HasResponse() bool {
	if o != nil && o.Response != nil {
		return true
	}

	return false
}

// SetResponse gets a reference to the given LdapUserSettings and assigns it to the Response field.
func (o *LdapUserSettingsResponse) SetResponse(v LdapUserSettings) {
	o.Response = &v
}

func (o LdapUserSettingsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Response != nil {
		toSerialize["response"] = o.Response
	}
	return json.Marshal(toSerialize)
}

type NullableLdapUserSettingsResponse struct {
	value *LdapUserSettingsResponse
	isSet bool
}

func (v NullableLdapUserSettingsResponse) Get() *LdapUserSettingsResponse {
	return v.value
}

func (v *NullableLdapUserSettingsResponse) Set(val *LdapUserSettingsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableLdapUserSettingsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableLdapUserSettingsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLdapUserSettingsResponse(val *LdapUserSettingsResponse) *NullableLdapUserSettingsResponse {
	return &NullableLdapUserSettingsResponse{value: val, isSet: true}
}

func (v NullableLdapUserSettingsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLdapUserSettingsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


