/*
VNS3 Controller API

Cohesive networks VNS3 provides complete control of your network's addressing, routes, rules and edge enabling a secure, connected and reactive cloud network. 

API version: 5.1.5
Contact: support@cohesive.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// PutEnableLdapRequest struct for PutEnableLdapRequest
type PutEnableLdapRequest struct {
	// True to enable LDAP
	Enabled bool `json:"enabled"`
}

// NewPutEnableLdapRequest instantiates a new PutEnableLdapRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPutEnableLdapRequest(enabled bool) *PutEnableLdapRequest {
	this := PutEnableLdapRequest{}
	this.Enabled = enabled
	return &this
}

// NewPutEnableLdapRequestWithDefaults instantiates a new PutEnableLdapRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPutEnableLdapRequestWithDefaults() *PutEnableLdapRequest {
	this := PutEnableLdapRequest{}
	return &this
}

// GetEnabled returns the Enabled field value
func (o *PutEnableLdapRequest) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *PutEnableLdapRequest) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *PutEnableLdapRequest) SetEnabled(v bool) {
	o.Enabled = v
}

func (o PutEnableLdapRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["enabled"] = o.Enabled
	}
	return json.Marshal(toSerialize)
}

type NullablePutEnableLdapRequest struct {
	value *PutEnableLdapRequest
	isSet bool
}

func (v NullablePutEnableLdapRequest) Get() *PutEnableLdapRequest {
	return v.value
}

func (v *NullablePutEnableLdapRequest) Set(val *PutEnableLdapRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePutEnableLdapRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePutEnableLdapRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePutEnableLdapRequest(val *PutEnableLdapRequest) *NullablePutEnableLdapRequest {
	return &NullablePutEnableLdapRequest{value: val, isSet: true}
}

func (v NullablePutEnableLdapRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePutEnableLdapRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


