/*
VNS3 Controller API

Cohesive networks VNS3 provides complete control of your network's addressing, routes, rules and edge enabling a secure, connected and reactive cloud network. 

API version: 5.1.5
Contact: support@cohesive.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// PostTestLdapGroupSchemaSettings200Response struct for PostTestLdapGroupSchemaSettings200Response
type PostTestLdapGroupSchemaSettings200Response struct {
	Response []PostTestLdapGroupSchemaSettings200ResponseResponseInner `json:"response,omitempty"`
}

// NewPostTestLdapGroupSchemaSettings200Response instantiates a new PostTestLdapGroupSchemaSettings200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostTestLdapGroupSchemaSettings200Response() *PostTestLdapGroupSchemaSettings200Response {
	this := PostTestLdapGroupSchemaSettings200Response{}
	return &this
}

// NewPostTestLdapGroupSchemaSettings200ResponseWithDefaults instantiates a new PostTestLdapGroupSchemaSettings200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostTestLdapGroupSchemaSettings200ResponseWithDefaults() *PostTestLdapGroupSchemaSettings200Response {
	this := PostTestLdapGroupSchemaSettings200Response{}
	return &this
}

// GetResponse returns the Response field value if set, zero value otherwise.
func (o *PostTestLdapGroupSchemaSettings200Response) GetResponse() []PostTestLdapGroupSchemaSettings200ResponseResponseInner {
	if o == nil || o.Response == nil {
		var ret []PostTestLdapGroupSchemaSettings200ResponseResponseInner
		return ret
	}
	return o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostTestLdapGroupSchemaSettings200Response) GetResponseOk() ([]PostTestLdapGroupSchemaSettings200ResponseResponseInner, bool) {
	if o == nil || o.Response == nil {
		return nil, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *PostTestLdapGroupSchemaSettings200Response) HasResponse() bool {
	if o != nil && o.Response != nil {
		return true
	}

	return false
}

// SetResponse gets a reference to the given []PostTestLdapGroupSchemaSettings200ResponseResponseInner and assigns it to the Response field.
func (o *PostTestLdapGroupSchemaSettings200Response) SetResponse(v []PostTestLdapGroupSchemaSettings200ResponseResponseInner) {
	o.Response = v
}

func (o PostTestLdapGroupSchemaSettings200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Response != nil {
		toSerialize["response"] = o.Response
	}
	return json.Marshal(toSerialize)
}

type NullablePostTestLdapGroupSchemaSettings200Response struct {
	value *PostTestLdapGroupSchemaSettings200Response
	isSet bool
}

func (v NullablePostTestLdapGroupSchemaSettings200Response) Get() *PostTestLdapGroupSchemaSettings200Response {
	return v.value
}

func (v *NullablePostTestLdapGroupSchemaSettings200Response) Set(val *PostTestLdapGroupSchemaSettings200Response) {
	v.value = val
	v.isSet = true
}

func (v NullablePostTestLdapGroupSchemaSettings200Response) IsSet() bool {
	return v.isSet
}

func (v *NullablePostTestLdapGroupSchemaSettings200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostTestLdapGroupSchemaSettings200Response(val *PostTestLdapGroupSchemaSettings200Response) *NullablePostTestLdapGroupSchemaSettings200Response {
	return &NullablePostTestLdapGroupSchemaSettings200Response{value: val, isSet: true}
}

func (v NullablePostTestLdapGroupSchemaSettings200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostTestLdapGroupSchemaSettings200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


