/*
VNS3 Controller API

Cohesive networks VNS3 provides complete control of your network's addressing, routes, rules and edge enabling a secure, connected and reactive cloud network. 

API version: 5.1.5
Contact: support@cohesive.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// LdapVpnSchemaSettingsResponse struct for LdapVpnSchemaSettingsResponse
type LdapVpnSchemaSettingsResponse struct {
	Response *LdapVpnSchemaSettings `json:"response,omitempty"`
}

// NewLdapVpnSchemaSettingsResponse instantiates a new LdapVpnSchemaSettingsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLdapVpnSchemaSettingsResponse() *LdapVpnSchemaSettingsResponse {
	this := LdapVpnSchemaSettingsResponse{}
	return &this
}

// NewLdapVpnSchemaSettingsResponseWithDefaults instantiates a new LdapVpnSchemaSettingsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLdapVpnSchemaSettingsResponseWithDefaults() *LdapVpnSchemaSettingsResponse {
	this := LdapVpnSchemaSettingsResponse{}
	return &this
}

// GetResponse returns the Response field value if set, zero value otherwise.
func (o *LdapVpnSchemaSettingsResponse) GetResponse() LdapVpnSchemaSettings {
	if o == nil || o.Response == nil {
		var ret LdapVpnSchemaSettings
		return ret
	}
	return *o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LdapVpnSchemaSettingsResponse) GetResponseOk() (*LdapVpnSchemaSettings, bool) {
	if o == nil || o.Response == nil {
		return nil, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *LdapVpnSchemaSettingsResponse) HasResponse() bool {
	if o != nil && o.Response != nil {
		return true
	}

	return false
}

// SetResponse gets a reference to the given LdapVpnSchemaSettings and assigns it to the Response field.
func (o *LdapVpnSchemaSettingsResponse) SetResponse(v LdapVpnSchemaSettings) {
	o.Response = &v
}

func (o LdapVpnSchemaSettingsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Response != nil {
		toSerialize["response"] = o.Response
	}
	return json.Marshal(toSerialize)
}

type NullableLdapVpnSchemaSettingsResponse struct {
	value *LdapVpnSchemaSettingsResponse
	isSet bool
}

func (v NullableLdapVpnSchemaSettingsResponse) Get() *LdapVpnSchemaSettingsResponse {
	return v.value
}

func (v *NullableLdapVpnSchemaSettingsResponse) Set(val *LdapVpnSchemaSettingsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableLdapVpnSchemaSettingsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableLdapVpnSchemaSettingsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLdapVpnSchemaSettingsResponse(val *LdapVpnSchemaSettingsResponse) *NullableLdapVpnSchemaSettingsResponse {
	return &NullableLdapVpnSchemaSettingsResponse{value: val, isSet: true}
}

func (v NullableLdapVpnSchemaSettingsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLdapVpnSchemaSettingsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


