/*
VNS3 Controller API

Cohesive networks VNS3 provides complete control of your network's addressing, routes, rules and edge enabling a secure, connected and reactive cloud network. 

API version: 5.1.5
Contact: support@cohesive.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// RoutesList struct for RoutesList
type RoutesList struct {
	Id *int32 `json:"id,omitempty"`
	Cidr *string `json:"cidr,omitempty"`
	Interface *string `json:"interface,omitempty"`
	Netmask *string `json:"netmask,omitempty"`
	Description *string `json:"description,omitempty"`
	Advertise *bool `json:"advertise,omitempty"`
	Enabled *bool `json:"enabled,omitempty"`
	Metric *int32 `json:"metric,omitempty"`
	Gateway *string `json:"gateway,omitempty"`
	Tunnel *RuntimeStatusIpsecValue `json:"tunnel,omitempty"`
}

// NewRoutesList instantiates a new RoutesList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoutesList() *RoutesList {
	this := RoutesList{}
	return &this
}

// NewRoutesListWithDefaults instantiates a new RoutesList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoutesListWithDefaults() *RoutesList {
	this := RoutesList{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *RoutesList) GetId() int32 {
	if o == nil || o.Id == nil {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutesList) GetIdOk() (*int32, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *RoutesList) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *RoutesList) SetId(v int32) {
	o.Id = &v
}

// GetCidr returns the Cidr field value if set, zero value otherwise.
func (o *RoutesList) GetCidr() string {
	if o == nil || o.Cidr == nil {
		var ret string
		return ret
	}
	return *o.Cidr
}

// GetCidrOk returns a tuple with the Cidr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutesList) GetCidrOk() (*string, bool) {
	if o == nil || o.Cidr == nil {
		return nil, false
	}
	return o.Cidr, true
}

// HasCidr returns a boolean if a field has been set.
func (o *RoutesList) HasCidr() bool {
	if o != nil && o.Cidr != nil {
		return true
	}

	return false
}

// SetCidr gets a reference to the given string and assigns it to the Cidr field.
func (o *RoutesList) SetCidr(v string) {
	o.Cidr = &v
}

// GetInterface returns the Interface field value if set, zero value otherwise.
func (o *RoutesList) GetInterface() string {
	if o == nil || o.Interface == nil {
		var ret string
		return ret
	}
	return *o.Interface
}

// GetInterfaceOk returns a tuple with the Interface field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutesList) GetInterfaceOk() (*string, bool) {
	if o == nil || o.Interface == nil {
		return nil, false
	}
	return o.Interface, true
}

// HasInterface returns a boolean if a field has been set.
func (o *RoutesList) HasInterface() bool {
	if o != nil && o.Interface != nil {
		return true
	}

	return false
}

// SetInterface gets a reference to the given string and assigns it to the Interface field.
func (o *RoutesList) SetInterface(v string) {
	o.Interface = &v
}

// GetNetmask returns the Netmask field value if set, zero value otherwise.
func (o *RoutesList) GetNetmask() string {
	if o == nil || o.Netmask == nil {
		var ret string
		return ret
	}
	return *o.Netmask
}

// GetNetmaskOk returns a tuple with the Netmask field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutesList) GetNetmaskOk() (*string, bool) {
	if o == nil || o.Netmask == nil {
		return nil, false
	}
	return o.Netmask, true
}

// HasNetmask returns a boolean if a field has been set.
func (o *RoutesList) HasNetmask() bool {
	if o != nil && o.Netmask != nil {
		return true
	}

	return false
}

// SetNetmask gets a reference to the given string and assigns it to the Netmask field.
func (o *RoutesList) SetNetmask(v string) {
	o.Netmask = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *RoutesList) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutesList) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *RoutesList) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *RoutesList) SetDescription(v string) {
	o.Description = &v
}

// GetAdvertise returns the Advertise field value if set, zero value otherwise.
func (o *RoutesList) GetAdvertise() bool {
	if o == nil || o.Advertise == nil {
		var ret bool
		return ret
	}
	return *o.Advertise
}

// GetAdvertiseOk returns a tuple with the Advertise field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutesList) GetAdvertiseOk() (*bool, bool) {
	if o == nil || o.Advertise == nil {
		return nil, false
	}
	return o.Advertise, true
}

// HasAdvertise returns a boolean if a field has been set.
func (o *RoutesList) HasAdvertise() bool {
	if o != nil && o.Advertise != nil {
		return true
	}

	return false
}

// SetAdvertise gets a reference to the given bool and assigns it to the Advertise field.
func (o *RoutesList) SetAdvertise(v bool) {
	o.Advertise = &v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *RoutesList) GetEnabled() bool {
	if o == nil || o.Enabled == nil {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutesList) GetEnabledOk() (*bool, bool) {
	if o == nil || o.Enabled == nil {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *RoutesList) HasEnabled() bool {
	if o != nil && o.Enabled != nil {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *RoutesList) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetMetric returns the Metric field value if set, zero value otherwise.
func (o *RoutesList) GetMetric() int32 {
	if o == nil || o.Metric == nil {
		var ret int32
		return ret
	}
	return *o.Metric
}

// GetMetricOk returns a tuple with the Metric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutesList) GetMetricOk() (*int32, bool) {
	if o == nil || o.Metric == nil {
		return nil, false
	}
	return o.Metric, true
}

// HasMetric returns a boolean if a field has been set.
func (o *RoutesList) HasMetric() bool {
	if o != nil && o.Metric != nil {
		return true
	}

	return false
}

// SetMetric gets a reference to the given int32 and assigns it to the Metric field.
func (o *RoutesList) SetMetric(v int32) {
	o.Metric = &v
}

// GetGateway returns the Gateway field value if set, zero value otherwise.
func (o *RoutesList) GetGateway() string {
	if o == nil || o.Gateway == nil {
		var ret string
		return ret
	}
	return *o.Gateway
}

// GetGatewayOk returns a tuple with the Gateway field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutesList) GetGatewayOk() (*string, bool) {
	if o == nil || o.Gateway == nil {
		return nil, false
	}
	return o.Gateway, true
}

// HasGateway returns a boolean if a field has been set.
func (o *RoutesList) HasGateway() bool {
	if o != nil && o.Gateway != nil {
		return true
	}

	return false
}

// SetGateway gets a reference to the given string and assigns it to the Gateway field.
func (o *RoutesList) SetGateway(v string) {
	o.Gateway = &v
}

// GetTunnel returns the Tunnel field value if set, zero value otherwise.
func (o *RoutesList) GetTunnel() RuntimeStatusIpsecValue {
	if o == nil || o.Tunnel == nil {
		var ret RuntimeStatusIpsecValue
		return ret
	}
	return *o.Tunnel
}

// GetTunnelOk returns a tuple with the Tunnel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutesList) GetTunnelOk() (*RuntimeStatusIpsecValue, bool) {
	if o == nil || o.Tunnel == nil {
		return nil, false
	}
	return o.Tunnel, true
}

// HasTunnel returns a boolean if a field has been set.
func (o *RoutesList) HasTunnel() bool {
	if o != nil && o.Tunnel != nil {
		return true
	}

	return false
}

// SetTunnel gets a reference to the given RuntimeStatusIpsecValue and assigns it to the Tunnel field.
func (o *RoutesList) SetTunnel(v RuntimeStatusIpsecValue) {
	o.Tunnel = &v
}

func (o RoutesList) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Cidr != nil {
		toSerialize["cidr"] = o.Cidr
	}
	if o.Interface != nil {
		toSerialize["interface"] = o.Interface
	}
	if o.Netmask != nil {
		toSerialize["netmask"] = o.Netmask
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.Advertise != nil {
		toSerialize["advertise"] = o.Advertise
	}
	if o.Enabled != nil {
		toSerialize["enabled"] = o.Enabled
	}
	if o.Metric != nil {
		toSerialize["metric"] = o.Metric
	}
	if o.Gateway != nil {
		toSerialize["gateway"] = o.Gateway
	}
	if o.Tunnel != nil {
		toSerialize["tunnel"] = o.Tunnel
	}
	return json.Marshal(toSerialize)
}

type NullableRoutesList struct {
	value *RoutesList
	isSet bool
}

func (v NullableRoutesList) Get() *RoutesList {
	return v.value
}

func (v *NullableRoutesList) Set(val *RoutesList) {
	v.value = val
	v.isSet = true
}

func (v NullableRoutesList) IsSet() bool {
	return v.isSet
}

func (v *NullableRoutesList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoutesList(val *RoutesList) *NullableRoutesList {
	return &NullableRoutesList{value: val, isSet: true}
}

func (v NullableRoutesList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoutesList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


