/*
VNS3 Controller API

Cohesive networks VNS3 provides complete control of your network's addressing, routes, rules and edge enabling a secure, connected and reactive cloud network. 

API version: 5.1.5
Contact: support@cohesive.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// CreateFWSubgroupRequest - struct for CreateFWSubgroupRequest
type CreateFWSubgroupRequest struct {
	Interface{} *interface{}
}

// interface{}AsCreateFWSubgroupRequest is a convenience function that returns interface{} wrapped in CreateFWSubgroupRequest
func Interface{}AsCreateFWSubgroupRequest(v *interface{}) CreateFWSubgroupRequest {
	return CreateFWSubgroupRequest{
		Interface{}: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *CreateFWSubgroupRequest) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into Interface{}
	err = newStrictDecoder(data).Decode(&dst.Interface{})
	if err == nil {
		jsonInterface{}, _ := json.Marshal(dst.Interface{})
		if string(jsonInterface{}) == "{}" { // empty struct
			dst.Interface{} = nil
		} else {
			match++
		}
	} else {
		dst.Interface{} = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.Interface{} = nil

		return fmt.Errorf("Data matches more than one schema in oneOf(CreateFWSubgroupRequest)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("Data failed to match schemas in oneOf(CreateFWSubgroupRequest)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src CreateFWSubgroupRequest) MarshalJSON() ([]byte, error) {
	if src.Interface{} != nil {
		return json.Marshal(&src.Interface{})
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *CreateFWSubgroupRequest) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.Interface{} != nil {
		return obj.Interface{}
	}

	// all schemas are nil
	return nil
}

type NullableCreateFWSubgroupRequest struct {
	value *CreateFWSubgroupRequest
	isSet bool
}

func (v NullableCreateFWSubgroupRequest) Get() *CreateFWSubgroupRequest {
	return v.value
}

func (v *NullableCreateFWSubgroupRequest) Set(val *CreateFWSubgroupRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateFWSubgroupRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateFWSubgroupRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateFWSubgroupRequest(val *CreateFWSubgroupRequest) *NullableCreateFWSubgroupRequest {
	return &NullableCreateFWSubgroupRequest{value: val, isSet: true}
}

func (v NullableCreateFWSubgroupRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateFWSubgroupRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


