/*
VNS3 Controller API

Cohesive networks VNS3 provides complete control of your network's addressing, routes, rules and edge enabling a secure, connected and reactive cloud network. 

API version: 5.1.5
Contact: support@cohesive.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// FirewallFWSetListResponse struct for FirewallFWSetListResponse
type FirewallFWSetListResponse struct {
	Response []string `json:"response,omitempty"`
}

// NewFirewallFWSetListResponse instantiates a new FirewallFWSetListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFirewallFWSetListResponse() *FirewallFWSetListResponse {
	this := FirewallFWSetListResponse{}
	return &this
}

// NewFirewallFWSetListResponseWithDefaults instantiates a new FirewallFWSetListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFirewallFWSetListResponseWithDefaults() *FirewallFWSetListResponse {
	this := FirewallFWSetListResponse{}
	return &this
}

// GetResponse returns the Response field value if set, zero value otherwise.
func (o *FirewallFWSetListResponse) GetResponse() []string {
	if o == nil || o.Response == nil {
		var ret []string
		return ret
	}
	return o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FirewallFWSetListResponse) GetResponseOk() ([]string, bool) {
	if o == nil || o.Response == nil {
		return nil, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *FirewallFWSetListResponse) HasResponse() bool {
	if o != nil && o.Response != nil {
		return true
	}

	return false
}

// SetResponse gets a reference to the given []string and assigns it to the Response field.
func (o *FirewallFWSetListResponse) SetResponse(v []string) {
	o.Response = v
}

func (o FirewallFWSetListResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Response != nil {
		toSerialize["response"] = o.Response
	}
	return json.Marshal(toSerialize)
}

type NullableFirewallFWSetListResponse struct {
	value *FirewallFWSetListResponse
	isSet bool
}

func (v NullableFirewallFWSetListResponse) Get() *FirewallFWSetListResponse {
	return v.value
}

func (v *NullableFirewallFWSetListResponse) Set(val *FirewallFWSetListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableFirewallFWSetListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableFirewallFWSetListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFirewallFWSetListResponse(val *FirewallFWSetListResponse) *NullableFirewallFWSetListResponse {
	return &NullableFirewallFWSetListResponse{value: val, isSet: true}
}

func (v NullableFirewallFWSetListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFirewallFWSetListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


