/*
VNS3 Controller API

Cohesive networks VNS3 provides complete control of your network's addressing, routes, rules and edge enabling a secure, connected and reactive cloud network. 

API version: 5.1.5
Contact: support@cohesive.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// PutFirewallRuleRequest struct for PutFirewallRuleRequest
type PutFirewallRuleRequest struct {
	// New-line delimited string of firewall rules.
	Rules string `json:"rules"`
}

// NewPutFirewallRuleRequest instantiates a new PutFirewallRuleRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPutFirewallRuleRequest(rules string) *PutFirewallRuleRequest {
	this := PutFirewallRuleRequest{}
	this.Rules = rules
	return &this
}

// NewPutFirewallRuleRequestWithDefaults instantiates a new PutFirewallRuleRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPutFirewallRuleRequestWithDefaults() *PutFirewallRuleRequest {
	this := PutFirewallRuleRequest{}
	return &this
}

// GetRules returns the Rules field value
func (o *PutFirewallRuleRequest) GetRules() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Rules
}

// GetRulesOk returns a tuple with the Rules field value
// and a boolean to check if the value has been set.
func (o *PutFirewallRuleRequest) GetRulesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Rules, true
}

// SetRules sets field value
func (o *PutFirewallRuleRequest) SetRules(v string) {
	o.Rules = v
}

func (o PutFirewallRuleRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["rules"] = o.Rules
	}
	return json.Marshal(toSerialize)
}

type NullablePutFirewallRuleRequest struct {
	value *PutFirewallRuleRequest
	isSet bool
}

func (v NullablePutFirewallRuleRequest) Get() *PutFirewallRuleRequest {
	return v.value
}

func (v *NullablePutFirewallRuleRequest) Set(val *PutFirewallRuleRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePutFirewallRuleRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePutFirewallRuleRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePutFirewallRuleRequest(val *PutFirewallRuleRequest) *NullablePutFirewallRuleRequest {
	return &NullablePutFirewallRuleRequest{value: val, isSet: true}
}

func (v NullablePutFirewallRuleRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePutFirewallRuleRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


