/*
VNS3 Controller API

Cohesive networks VNS3 provides complete control of your network's addressing, routes, rules and edge enabling a secure, connected and reactive cloud network. 

API version: 5.1.5
Contact: support@cohesive.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// FirewallFWSetData struct for FirewallFWSetData
type FirewallFWSetData struct {
	Status *string `json:"status,omitempty"`
	// Begins with name and is followed by Firewall rules. This is an indexed rule that allows for speedy matching on IPs
	Rules *string `json:"rules,omitempty"`
}

// NewFirewallFWSetData instantiates a new FirewallFWSetData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFirewallFWSetData() *FirewallFWSetData {
	this := FirewallFWSetData{}
	return &this
}

// NewFirewallFWSetDataWithDefaults instantiates a new FirewallFWSetData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFirewallFWSetDataWithDefaults() *FirewallFWSetData {
	this := FirewallFWSetData{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *FirewallFWSetData) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FirewallFWSetData) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *FirewallFWSetData) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *FirewallFWSetData) SetStatus(v string) {
	o.Status = &v
}

// GetRules returns the Rules field value if set, zero value otherwise.
func (o *FirewallFWSetData) GetRules() string {
	if o == nil || o.Rules == nil {
		var ret string
		return ret
	}
	return *o.Rules
}

// GetRulesOk returns a tuple with the Rules field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FirewallFWSetData) GetRulesOk() (*string, bool) {
	if o == nil || o.Rules == nil {
		return nil, false
	}
	return o.Rules, true
}

// HasRules returns a boolean if a field has been set.
func (o *FirewallFWSetData) HasRules() bool {
	if o != nil && o.Rules != nil {
		return true
	}

	return false
}

// SetRules gets a reference to the given string and assigns it to the Rules field.
func (o *FirewallFWSetData) SetRules(v string) {
	o.Rules = &v
}

func (o FirewallFWSetData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if o.Rules != nil {
		toSerialize["rules"] = o.Rules
	}
	return json.Marshal(toSerialize)
}

type NullableFirewallFWSetData struct {
	value *FirewallFWSetData
	isSet bool
}

func (v NullableFirewallFWSetData) Get() *FirewallFWSetData {
	return v.value
}

func (v *NullableFirewallFWSetData) Set(val *FirewallFWSetData) {
	v.value = val
	v.isSet = true
}

func (v NullableFirewallFWSetData) IsSet() bool {
	return v.isSet
}

func (v *NullableFirewallFWSetData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFirewallFWSetData(val *FirewallFWSetData) *NullableFirewallFWSetData {
	return &NullableFirewallFWSetData{value: val, isSet: true}
}

func (v NullableFirewallFWSetData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFirewallFWSetData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


