/*
VNS3 Controller API

Cohesive networks VNS3 provides complete control of your network's addressing, routes, rules and edge enabling a secure, connected and reactive cloud network. 

API version: 5.1.5
Contact: support@cohesive.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// LdapVpnSchemaSettings struct for LdapVpnSchemaSettings
type LdapVpnSchemaSettings struct {
	VpnAuthEnabled *bool `json:"vpn_auth_enabled,omitempty"`
	VpnAuthProvider *string `json:"vpn_auth_provider,omitempty"`
	// Base DN from which to search for Groups
	VpnGroupBase *string `json:"vpn_group_base,omitempty"`
	// Attribute type for the Groups
	VpnGroupIdAttribute *string `json:"vpn_group_id_attribute,omitempty"`
	// Search filter for Groups
	VpnGroupListFilter *string `json:"vpn_group_list_filter,omitempty"`
	// Attribute used to search for a user within the Group
	VpnGroupMemberAttribute *string `json:"vpn_group_member_attribute,omitempty"`
	// Format of the Group Member attribute
	VpnGroupMemberAttrFormat *string `json:"vpn_group_member_attr_format,omitempty"`
	// Format of the Group Member attribute
	VpnGroupSearchScope *string `json:"vpn_group_search_scope,omitempty"`
	VpnGroupOtp *bool `json:"vpn_group_otp,omitempty"`
	VpnGroupOtpUrl *string `json:"vpn_group_otp_url,omitempty"`
}

// NewLdapVpnSchemaSettings instantiates a new LdapVpnSchemaSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLdapVpnSchemaSettings() *LdapVpnSchemaSettings {
	this := LdapVpnSchemaSettings{}
	var vpnGroupMemberAttrFormat string = "UserDN"
	this.VpnGroupMemberAttrFormat = &vpnGroupMemberAttrFormat
	var vpnGroupSearchScope string = "subtree"
	this.VpnGroupSearchScope = &vpnGroupSearchScope
	return &this
}

// NewLdapVpnSchemaSettingsWithDefaults instantiates a new LdapVpnSchemaSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLdapVpnSchemaSettingsWithDefaults() *LdapVpnSchemaSettings {
	this := LdapVpnSchemaSettings{}
	var vpnGroupMemberAttrFormat string = "UserDN"
	this.VpnGroupMemberAttrFormat = &vpnGroupMemberAttrFormat
	var vpnGroupSearchScope string = "subtree"
	this.VpnGroupSearchScope = &vpnGroupSearchScope
	return &this
}

// GetVpnAuthEnabled returns the VpnAuthEnabled field value if set, zero value otherwise.
func (o *LdapVpnSchemaSettings) GetVpnAuthEnabled() bool {
	if o == nil || o.VpnAuthEnabled == nil {
		var ret bool
		return ret
	}
	return *o.VpnAuthEnabled
}

// GetVpnAuthEnabledOk returns a tuple with the VpnAuthEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LdapVpnSchemaSettings) GetVpnAuthEnabledOk() (*bool, bool) {
	if o == nil || o.VpnAuthEnabled == nil {
		return nil, false
	}
	return o.VpnAuthEnabled, true
}

// HasVpnAuthEnabled returns a boolean if a field has been set.
func (o *LdapVpnSchemaSettings) HasVpnAuthEnabled() bool {
	if o != nil && o.VpnAuthEnabled != nil {
		return true
	}

	return false
}

// SetVpnAuthEnabled gets a reference to the given bool and assigns it to the VpnAuthEnabled field.
func (o *LdapVpnSchemaSettings) SetVpnAuthEnabled(v bool) {
	o.VpnAuthEnabled = &v
}

// GetVpnAuthProvider returns the VpnAuthProvider field value if set, zero value otherwise.
func (o *LdapVpnSchemaSettings) GetVpnAuthProvider() string {
	if o == nil || o.VpnAuthProvider == nil {
		var ret string
		return ret
	}
	return *o.VpnAuthProvider
}

// GetVpnAuthProviderOk returns a tuple with the VpnAuthProvider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LdapVpnSchemaSettings) GetVpnAuthProviderOk() (*string, bool) {
	if o == nil || o.VpnAuthProvider == nil {
		return nil, false
	}
	return o.VpnAuthProvider, true
}

// HasVpnAuthProvider returns a boolean if a field has been set.
func (o *LdapVpnSchemaSettings) HasVpnAuthProvider() bool {
	if o != nil && o.VpnAuthProvider != nil {
		return true
	}

	return false
}

// SetVpnAuthProvider gets a reference to the given string and assigns it to the VpnAuthProvider field.
func (o *LdapVpnSchemaSettings) SetVpnAuthProvider(v string) {
	o.VpnAuthProvider = &v
}

// GetVpnGroupBase returns the VpnGroupBase field value if set, zero value otherwise.
func (o *LdapVpnSchemaSettings) GetVpnGroupBase() string {
	if o == nil || o.VpnGroupBase == nil {
		var ret string
		return ret
	}
	return *o.VpnGroupBase
}

// GetVpnGroupBaseOk returns a tuple with the VpnGroupBase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LdapVpnSchemaSettings) GetVpnGroupBaseOk() (*string, bool) {
	if o == nil || o.VpnGroupBase == nil {
		return nil, false
	}
	return o.VpnGroupBase, true
}

// HasVpnGroupBase returns a boolean if a field has been set.
func (o *LdapVpnSchemaSettings) HasVpnGroupBase() bool {
	if o != nil && o.VpnGroupBase != nil {
		return true
	}

	return false
}

// SetVpnGroupBase gets a reference to the given string and assigns it to the VpnGroupBase field.
func (o *LdapVpnSchemaSettings) SetVpnGroupBase(v string) {
	o.VpnGroupBase = &v
}

// GetVpnGroupIdAttribute returns the VpnGroupIdAttribute field value if set, zero value otherwise.
func (o *LdapVpnSchemaSettings) GetVpnGroupIdAttribute() string {
	if o == nil || o.VpnGroupIdAttribute == nil {
		var ret string
		return ret
	}
	return *o.VpnGroupIdAttribute
}

// GetVpnGroupIdAttributeOk returns a tuple with the VpnGroupIdAttribute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LdapVpnSchemaSettings) GetVpnGroupIdAttributeOk() (*string, bool) {
	if o == nil || o.VpnGroupIdAttribute == nil {
		return nil, false
	}
	return o.VpnGroupIdAttribute, true
}

// HasVpnGroupIdAttribute returns a boolean if a field has been set.
func (o *LdapVpnSchemaSettings) HasVpnGroupIdAttribute() bool {
	if o != nil && o.VpnGroupIdAttribute != nil {
		return true
	}

	return false
}

// SetVpnGroupIdAttribute gets a reference to the given string and assigns it to the VpnGroupIdAttribute field.
func (o *LdapVpnSchemaSettings) SetVpnGroupIdAttribute(v string) {
	o.VpnGroupIdAttribute = &v
}

// GetVpnGroupListFilter returns the VpnGroupListFilter field value if set, zero value otherwise.
func (o *LdapVpnSchemaSettings) GetVpnGroupListFilter() string {
	if o == nil || o.VpnGroupListFilter == nil {
		var ret string
		return ret
	}
	return *o.VpnGroupListFilter
}

// GetVpnGroupListFilterOk returns a tuple with the VpnGroupListFilter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LdapVpnSchemaSettings) GetVpnGroupListFilterOk() (*string, bool) {
	if o == nil || o.VpnGroupListFilter == nil {
		return nil, false
	}
	return o.VpnGroupListFilter, true
}

// HasVpnGroupListFilter returns a boolean if a field has been set.
func (o *LdapVpnSchemaSettings) HasVpnGroupListFilter() bool {
	if o != nil && o.VpnGroupListFilter != nil {
		return true
	}

	return false
}

// SetVpnGroupListFilter gets a reference to the given string and assigns it to the VpnGroupListFilter field.
func (o *LdapVpnSchemaSettings) SetVpnGroupListFilter(v string) {
	o.VpnGroupListFilter = &v
}

// GetVpnGroupMemberAttribute returns the VpnGroupMemberAttribute field value if set, zero value otherwise.
func (o *LdapVpnSchemaSettings) GetVpnGroupMemberAttribute() string {
	if o == nil || o.VpnGroupMemberAttribute == nil {
		var ret string
		return ret
	}
	return *o.VpnGroupMemberAttribute
}

// GetVpnGroupMemberAttributeOk returns a tuple with the VpnGroupMemberAttribute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LdapVpnSchemaSettings) GetVpnGroupMemberAttributeOk() (*string, bool) {
	if o == nil || o.VpnGroupMemberAttribute == nil {
		return nil, false
	}
	return o.VpnGroupMemberAttribute, true
}

// HasVpnGroupMemberAttribute returns a boolean if a field has been set.
func (o *LdapVpnSchemaSettings) HasVpnGroupMemberAttribute() bool {
	if o != nil && o.VpnGroupMemberAttribute != nil {
		return true
	}

	return false
}

// SetVpnGroupMemberAttribute gets a reference to the given string and assigns it to the VpnGroupMemberAttribute field.
func (o *LdapVpnSchemaSettings) SetVpnGroupMemberAttribute(v string) {
	o.VpnGroupMemberAttribute = &v
}

// GetVpnGroupMemberAttrFormat returns the VpnGroupMemberAttrFormat field value if set, zero value otherwise.
func (o *LdapVpnSchemaSettings) GetVpnGroupMemberAttrFormat() string {
	if o == nil || o.VpnGroupMemberAttrFormat == nil {
		var ret string
		return ret
	}
	return *o.VpnGroupMemberAttrFormat
}

// GetVpnGroupMemberAttrFormatOk returns a tuple with the VpnGroupMemberAttrFormat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LdapVpnSchemaSettings) GetVpnGroupMemberAttrFormatOk() (*string, bool) {
	if o == nil || o.VpnGroupMemberAttrFormat == nil {
		return nil, false
	}
	return o.VpnGroupMemberAttrFormat, true
}

// HasVpnGroupMemberAttrFormat returns a boolean if a field has been set.
func (o *LdapVpnSchemaSettings) HasVpnGroupMemberAttrFormat() bool {
	if o != nil && o.VpnGroupMemberAttrFormat != nil {
		return true
	}

	return false
}

// SetVpnGroupMemberAttrFormat gets a reference to the given string and assigns it to the VpnGroupMemberAttrFormat field.
func (o *LdapVpnSchemaSettings) SetVpnGroupMemberAttrFormat(v string) {
	o.VpnGroupMemberAttrFormat = &v
}

// GetVpnGroupSearchScope returns the VpnGroupSearchScope field value if set, zero value otherwise.
func (o *LdapVpnSchemaSettings) GetVpnGroupSearchScope() string {
	if o == nil || o.VpnGroupSearchScope == nil {
		var ret string
		return ret
	}
	return *o.VpnGroupSearchScope
}

// GetVpnGroupSearchScopeOk returns a tuple with the VpnGroupSearchScope field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LdapVpnSchemaSettings) GetVpnGroupSearchScopeOk() (*string, bool) {
	if o == nil || o.VpnGroupSearchScope == nil {
		return nil, false
	}
	return o.VpnGroupSearchScope, true
}

// HasVpnGroupSearchScope returns a boolean if a field has been set.
func (o *LdapVpnSchemaSettings) HasVpnGroupSearchScope() bool {
	if o != nil && o.VpnGroupSearchScope != nil {
		return true
	}

	return false
}

// SetVpnGroupSearchScope gets a reference to the given string and assigns it to the VpnGroupSearchScope field.
func (o *LdapVpnSchemaSettings) SetVpnGroupSearchScope(v string) {
	o.VpnGroupSearchScope = &v
}

// GetVpnGroupOtp returns the VpnGroupOtp field value if set, zero value otherwise.
func (o *LdapVpnSchemaSettings) GetVpnGroupOtp() bool {
	if o == nil || o.VpnGroupOtp == nil {
		var ret bool
		return ret
	}
	return *o.VpnGroupOtp
}

// GetVpnGroupOtpOk returns a tuple with the VpnGroupOtp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LdapVpnSchemaSettings) GetVpnGroupOtpOk() (*bool, bool) {
	if o == nil || o.VpnGroupOtp == nil {
		return nil, false
	}
	return o.VpnGroupOtp, true
}

// HasVpnGroupOtp returns a boolean if a field has been set.
func (o *LdapVpnSchemaSettings) HasVpnGroupOtp() bool {
	if o != nil && o.VpnGroupOtp != nil {
		return true
	}

	return false
}

// SetVpnGroupOtp gets a reference to the given bool and assigns it to the VpnGroupOtp field.
func (o *LdapVpnSchemaSettings) SetVpnGroupOtp(v bool) {
	o.VpnGroupOtp = &v
}

// GetVpnGroupOtpUrl returns the VpnGroupOtpUrl field value if set, zero value otherwise.
func (o *LdapVpnSchemaSettings) GetVpnGroupOtpUrl() string {
	if o == nil || o.VpnGroupOtpUrl == nil {
		var ret string
		return ret
	}
	return *o.VpnGroupOtpUrl
}

// GetVpnGroupOtpUrlOk returns a tuple with the VpnGroupOtpUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LdapVpnSchemaSettings) GetVpnGroupOtpUrlOk() (*string, bool) {
	if o == nil || o.VpnGroupOtpUrl == nil {
		return nil, false
	}
	return o.VpnGroupOtpUrl, true
}

// HasVpnGroupOtpUrl returns a boolean if a field has been set.
func (o *LdapVpnSchemaSettings) HasVpnGroupOtpUrl() bool {
	if o != nil && o.VpnGroupOtpUrl != nil {
		return true
	}

	return false
}

// SetVpnGroupOtpUrl gets a reference to the given string and assigns it to the VpnGroupOtpUrl field.
func (o *LdapVpnSchemaSettings) SetVpnGroupOtpUrl(v string) {
	o.VpnGroupOtpUrl = &v
}

func (o LdapVpnSchemaSettings) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.VpnAuthEnabled != nil {
		toSerialize["vpn_auth_enabled"] = o.VpnAuthEnabled
	}
	if o.VpnAuthProvider != nil {
		toSerialize["vpn_auth_provider"] = o.VpnAuthProvider
	}
	if o.VpnGroupBase != nil {
		toSerialize["vpn_group_base"] = o.VpnGroupBase
	}
	if o.VpnGroupIdAttribute != nil {
		toSerialize["vpn_group_id_attribute"] = o.VpnGroupIdAttribute
	}
	if o.VpnGroupListFilter != nil {
		toSerialize["vpn_group_list_filter"] = o.VpnGroupListFilter
	}
	if o.VpnGroupMemberAttribute != nil {
		toSerialize["vpn_group_member_attribute"] = o.VpnGroupMemberAttribute
	}
	if o.VpnGroupMemberAttrFormat != nil {
		toSerialize["vpn_group_member_attr_format"] = o.VpnGroupMemberAttrFormat
	}
	if o.VpnGroupSearchScope != nil {
		toSerialize["vpn_group_search_scope"] = o.VpnGroupSearchScope
	}
	if o.VpnGroupOtp != nil {
		toSerialize["vpn_group_otp"] = o.VpnGroupOtp
	}
	if o.VpnGroupOtpUrl != nil {
		toSerialize["vpn_group_otp_url"] = o.VpnGroupOtpUrl
	}
	return json.Marshal(toSerialize)
}

type NullableLdapVpnSchemaSettings struct {
	value *LdapVpnSchemaSettings
	isSet bool
}

func (v NullableLdapVpnSchemaSettings) Get() *LdapVpnSchemaSettings {
	return v.value
}

func (v *NullableLdapVpnSchemaSettings) Set(val *LdapVpnSchemaSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableLdapVpnSchemaSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableLdapVpnSchemaSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLdapVpnSchemaSettings(val *LdapVpnSchemaSettings) *NullableLdapVpnSchemaSettings {
	return &NullableLdapVpnSchemaSettings{value: val, isSet: true}
}

func (v NullableLdapVpnSchemaSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLdapVpnSchemaSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


