/*
VNS3 Controller API

Cohesive networks VNS3 provides complete control of your network's addressing, routes, rules and edge enabling a secure, connected and reactive cloud network. 

API version: 5.1.5
Contact: support@cohesive.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// PutLdapVpnSchemaSettingsRequest struct for PutLdapVpnSchemaSettingsRequest
type PutLdapVpnSchemaSettingsRequest struct {
	// Enable use of LDAP through VPN. If true, other params required.
	VpnAuthEnabled bool `json:"vpn_auth_enabled"`
	// Base DN from which to search for Groups
	VpnGroupBase string `json:"vpn_group_base"`
	// Attribute type for the Groups
	VpnGroupIdAttribute string `json:"vpn_group_id_attribute"`
	// Search filter for Groups
	VpnGroupListFilter *string `json:"vpn_group_list_filter,omitempty"`
	// Attribute used to search for a user within the Group
	VpnGroupMemberAttribute string `json:"vpn_group_member_attribute"`
	// Format of the Group Member attribute
	VpnGroupMemberAttrFormat *string `json:"vpn_group_member_attr_format,omitempty"`
	// Search scope for filter
	VpnGroupSearchScope *string `json:"vpn_group_search_scope,omitempty"`
	// Use Google authenticator (OTP)?
	VpnGroupOtp *bool `json:"vpn_group_otp,omitempty"`
}

// NewPutLdapVpnSchemaSettingsRequest instantiates a new PutLdapVpnSchemaSettingsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPutLdapVpnSchemaSettingsRequest(vpnAuthEnabled bool, vpnGroupBase string, vpnGroupIdAttribute string, vpnGroupMemberAttribute string) *PutLdapVpnSchemaSettingsRequest {
	this := PutLdapVpnSchemaSettingsRequest{}
	this.VpnAuthEnabled = vpnAuthEnabled
	this.VpnGroupBase = vpnGroupBase
	this.VpnGroupIdAttribute = vpnGroupIdAttribute
	this.VpnGroupMemberAttribute = vpnGroupMemberAttribute
	var vpnGroupMemberAttrFormat string = "UserDN"
	this.VpnGroupMemberAttrFormat = &vpnGroupMemberAttrFormat
	var vpnGroupSearchScope string = "subtree"
	this.VpnGroupSearchScope = &vpnGroupSearchScope
	var vpnGroupOtp bool = false
	this.VpnGroupOtp = &vpnGroupOtp
	return &this
}

// NewPutLdapVpnSchemaSettingsRequestWithDefaults instantiates a new PutLdapVpnSchemaSettingsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPutLdapVpnSchemaSettingsRequestWithDefaults() *PutLdapVpnSchemaSettingsRequest {
	this := PutLdapVpnSchemaSettingsRequest{}
	var vpnGroupMemberAttrFormat string = "UserDN"
	this.VpnGroupMemberAttrFormat = &vpnGroupMemberAttrFormat
	var vpnGroupSearchScope string = "subtree"
	this.VpnGroupSearchScope = &vpnGroupSearchScope
	var vpnGroupOtp bool = false
	this.VpnGroupOtp = &vpnGroupOtp
	return &this
}

// GetVpnAuthEnabled returns the VpnAuthEnabled field value
func (o *PutLdapVpnSchemaSettingsRequest) GetVpnAuthEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.VpnAuthEnabled
}

// GetVpnAuthEnabledOk returns a tuple with the VpnAuthEnabled field value
// and a boolean to check if the value has been set.
func (o *PutLdapVpnSchemaSettingsRequest) GetVpnAuthEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VpnAuthEnabled, true
}

// SetVpnAuthEnabled sets field value
func (o *PutLdapVpnSchemaSettingsRequest) SetVpnAuthEnabled(v bool) {
	o.VpnAuthEnabled = v
}

// GetVpnGroupBase returns the VpnGroupBase field value
func (o *PutLdapVpnSchemaSettingsRequest) GetVpnGroupBase() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VpnGroupBase
}

// GetVpnGroupBaseOk returns a tuple with the VpnGroupBase field value
// and a boolean to check if the value has been set.
func (o *PutLdapVpnSchemaSettingsRequest) GetVpnGroupBaseOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VpnGroupBase, true
}

// SetVpnGroupBase sets field value
func (o *PutLdapVpnSchemaSettingsRequest) SetVpnGroupBase(v string) {
	o.VpnGroupBase = v
}

// GetVpnGroupIdAttribute returns the VpnGroupIdAttribute field value
func (o *PutLdapVpnSchemaSettingsRequest) GetVpnGroupIdAttribute() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VpnGroupIdAttribute
}

// GetVpnGroupIdAttributeOk returns a tuple with the VpnGroupIdAttribute field value
// and a boolean to check if the value has been set.
func (o *PutLdapVpnSchemaSettingsRequest) GetVpnGroupIdAttributeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VpnGroupIdAttribute, true
}

// SetVpnGroupIdAttribute sets field value
func (o *PutLdapVpnSchemaSettingsRequest) SetVpnGroupIdAttribute(v string) {
	o.VpnGroupIdAttribute = v
}

// GetVpnGroupListFilter returns the VpnGroupListFilter field value if set, zero value otherwise.
func (o *PutLdapVpnSchemaSettingsRequest) GetVpnGroupListFilter() string {
	if o == nil || o.VpnGroupListFilter == nil {
		var ret string
		return ret
	}
	return *o.VpnGroupListFilter
}

// GetVpnGroupListFilterOk returns a tuple with the VpnGroupListFilter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PutLdapVpnSchemaSettingsRequest) GetVpnGroupListFilterOk() (*string, bool) {
	if o == nil || o.VpnGroupListFilter == nil {
		return nil, false
	}
	return o.VpnGroupListFilter, true
}

// HasVpnGroupListFilter returns a boolean if a field has been set.
func (o *PutLdapVpnSchemaSettingsRequest) HasVpnGroupListFilter() bool {
	if o != nil && o.VpnGroupListFilter != nil {
		return true
	}

	return false
}

// SetVpnGroupListFilter gets a reference to the given string and assigns it to the VpnGroupListFilter field.
func (o *PutLdapVpnSchemaSettingsRequest) SetVpnGroupListFilter(v string) {
	o.VpnGroupListFilter = &v
}

// GetVpnGroupMemberAttribute returns the VpnGroupMemberAttribute field value
func (o *PutLdapVpnSchemaSettingsRequest) GetVpnGroupMemberAttribute() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VpnGroupMemberAttribute
}

// GetVpnGroupMemberAttributeOk returns a tuple with the VpnGroupMemberAttribute field value
// and a boolean to check if the value has been set.
func (o *PutLdapVpnSchemaSettingsRequest) GetVpnGroupMemberAttributeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VpnGroupMemberAttribute, true
}

// SetVpnGroupMemberAttribute sets field value
func (o *PutLdapVpnSchemaSettingsRequest) SetVpnGroupMemberAttribute(v string) {
	o.VpnGroupMemberAttribute = v
}

// GetVpnGroupMemberAttrFormat returns the VpnGroupMemberAttrFormat field value if set, zero value otherwise.
func (o *PutLdapVpnSchemaSettingsRequest) GetVpnGroupMemberAttrFormat() string {
	if o == nil || o.VpnGroupMemberAttrFormat == nil {
		var ret string
		return ret
	}
	return *o.VpnGroupMemberAttrFormat
}

// GetVpnGroupMemberAttrFormatOk returns a tuple with the VpnGroupMemberAttrFormat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PutLdapVpnSchemaSettingsRequest) GetVpnGroupMemberAttrFormatOk() (*string, bool) {
	if o == nil || o.VpnGroupMemberAttrFormat == nil {
		return nil, false
	}
	return o.VpnGroupMemberAttrFormat, true
}

// HasVpnGroupMemberAttrFormat returns a boolean if a field has been set.
func (o *PutLdapVpnSchemaSettingsRequest) HasVpnGroupMemberAttrFormat() bool {
	if o != nil && o.VpnGroupMemberAttrFormat != nil {
		return true
	}

	return false
}

// SetVpnGroupMemberAttrFormat gets a reference to the given string and assigns it to the VpnGroupMemberAttrFormat field.
func (o *PutLdapVpnSchemaSettingsRequest) SetVpnGroupMemberAttrFormat(v string) {
	o.VpnGroupMemberAttrFormat = &v
}

// GetVpnGroupSearchScope returns the VpnGroupSearchScope field value if set, zero value otherwise.
func (o *PutLdapVpnSchemaSettingsRequest) GetVpnGroupSearchScope() string {
	if o == nil || o.VpnGroupSearchScope == nil {
		var ret string
		return ret
	}
	return *o.VpnGroupSearchScope
}

// GetVpnGroupSearchScopeOk returns a tuple with the VpnGroupSearchScope field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PutLdapVpnSchemaSettingsRequest) GetVpnGroupSearchScopeOk() (*string, bool) {
	if o == nil || o.VpnGroupSearchScope == nil {
		return nil, false
	}
	return o.VpnGroupSearchScope, true
}

// HasVpnGroupSearchScope returns a boolean if a field has been set.
func (o *PutLdapVpnSchemaSettingsRequest) HasVpnGroupSearchScope() bool {
	if o != nil && o.VpnGroupSearchScope != nil {
		return true
	}

	return false
}

// SetVpnGroupSearchScope gets a reference to the given string and assigns it to the VpnGroupSearchScope field.
func (o *PutLdapVpnSchemaSettingsRequest) SetVpnGroupSearchScope(v string) {
	o.VpnGroupSearchScope = &v
}

// GetVpnGroupOtp returns the VpnGroupOtp field value if set, zero value otherwise.
func (o *PutLdapVpnSchemaSettingsRequest) GetVpnGroupOtp() bool {
	if o == nil || o.VpnGroupOtp == nil {
		var ret bool
		return ret
	}
	return *o.VpnGroupOtp
}

// GetVpnGroupOtpOk returns a tuple with the VpnGroupOtp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PutLdapVpnSchemaSettingsRequest) GetVpnGroupOtpOk() (*bool, bool) {
	if o == nil || o.VpnGroupOtp == nil {
		return nil, false
	}
	return o.VpnGroupOtp, true
}

// HasVpnGroupOtp returns a boolean if a field has been set.
func (o *PutLdapVpnSchemaSettingsRequest) HasVpnGroupOtp() bool {
	if o != nil && o.VpnGroupOtp != nil {
		return true
	}

	return false
}

// SetVpnGroupOtp gets a reference to the given bool and assigns it to the VpnGroupOtp field.
func (o *PutLdapVpnSchemaSettingsRequest) SetVpnGroupOtp(v bool) {
	o.VpnGroupOtp = &v
}

func (o PutLdapVpnSchemaSettingsRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["vpn_auth_enabled"] = o.VpnAuthEnabled
	}
	if true {
		toSerialize["vpn_group_base"] = o.VpnGroupBase
	}
	if true {
		toSerialize["vpn_group_id_attribute"] = o.VpnGroupIdAttribute
	}
	if o.VpnGroupListFilter != nil {
		toSerialize["vpn_group_list_filter"] = o.VpnGroupListFilter
	}
	if true {
		toSerialize["vpn_group_member_attribute"] = o.VpnGroupMemberAttribute
	}
	if o.VpnGroupMemberAttrFormat != nil {
		toSerialize["vpn_group_member_attr_format"] = o.VpnGroupMemberAttrFormat
	}
	if o.VpnGroupSearchScope != nil {
		toSerialize["vpn_group_search_scope"] = o.VpnGroupSearchScope
	}
	if o.VpnGroupOtp != nil {
		toSerialize["vpn_group_otp"] = o.VpnGroupOtp
	}
	return json.Marshal(toSerialize)
}

type NullablePutLdapVpnSchemaSettingsRequest struct {
	value *PutLdapVpnSchemaSettingsRequest
	isSet bool
}

func (v NullablePutLdapVpnSchemaSettingsRequest) Get() *PutLdapVpnSchemaSettingsRequest {
	return v.value
}

func (v *NullablePutLdapVpnSchemaSettingsRequest) Set(val *PutLdapVpnSchemaSettingsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePutLdapVpnSchemaSettingsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePutLdapVpnSchemaSettingsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePutLdapVpnSchemaSettingsRequest(val *PutLdapVpnSchemaSettingsRequest) *NullablePutLdapVpnSchemaSettingsRequest {
	return &NullablePutLdapVpnSchemaSettingsRequest{value: val, isSet: true}
}

func (v NullablePutLdapVpnSchemaSettingsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePutLdapVpnSchemaSettingsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


