/*
VNS3 Controller API

Cohesive networks VNS3 provides complete control of your network's addressing, routes, rules and edge enabling a secure, connected and reactive cloud network. 

API version: 5.1.5
Contact: support@cohesive.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// LdapVpnRadiusSettingsResponse struct for LdapVpnRadiusSettingsResponse
type LdapVpnRadiusSettingsResponse struct {
	Response *LdapVpnRadiusSettings `json:"response,omitempty"`
}

// NewLdapVpnRadiusSettingsResponse instantiates a new LdapVpnRadiusSettingsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLdapVpnRadiusSettingsResponse() *LdapVpnRadiusSettingsResponse {
	this := LdapVpnRadiusSettingsResponse{}
	return &this
}

// NewLdapVpnRadiusSettingsResponseWithDefaults instantiates a new LdapVpnRadiusSettingsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLdapVpnRadiusSettingsResponseWithDefaults() *LdapVpnRadiusSettingsResponse {
	this := LdapVpnRadiusSettingsResponse{}
	return &this
}

// GetResponse returns the Response field value if set, zero value otherwise.
func (o *LdapVpnRadiusSettingsResponse) GetResponse() LdapVpnRadiusSettings {
	if o == nil || o.Response == nil {
		var ret LdapVpnRadiusSettings
		return ret
	}
	return *o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LdapVpnRadiusSettingsResponse) GetResponseOk() (*LdapVpnRadiusSettings, bool) {
	if o == nil || o.Response == nil {
		return nil, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *LdapVpnRadiusSettingsResponse) HasResponse() bool {
	if o != nil && o.Response != nil {
		return true
	}

	return false
}

// SetResponse gets a reference to the given LdapVpnRadiusSettings and assigns it to the Response field.
func (o *LdapVpnRadiusSettingsResponse) SetResponse(v LdapVpnRadiusSettings) {
	o.Response = &v
}

func (o LdapVpnRadiusSettingsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Response != nil {
		toSerialize["response"] = o.Response
	}
	return json.Marshal(toSerialize)
}

type NullableLdapVpnRadiusSettingsResponse struct {
	value *LdapVpnRadiusSettingsResponse
	isSet bool
}

func (v NullableLdapVpnRadiusSettingsResponse) Get() *LdapVpnRadiusSettingsResponse {
	return v.value
}

func (v *NullableLdapVpnRadiusSettingsResponse) Set(val *LdapVpnRadiusSettingsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableLdapVpnRadiusSettingsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableLdapVpnRadiusSettingsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLdapVpnRadiusSettingsResponse(val *LdapVpnRadiusSettingsResponse) *NullableLdapVpnRadiusSettingsResponse {
	return &NullableLdapVpnRadiusSettingsResponse{value: val, isSet: true}
}

func (v NullableLdapVpnRadiusSettingsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLdapVpnRadiusSettingsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


