/*
VNS3 Controller API

Cohesive networks VNS3 provides complete control of your network's addressing, routes, rules and edge enabling a secure, connected and reactive cloud network. 

API version: 5.1.5
Contact: support@cohesive.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// LdapSettingsResponse struct for LdapSettingsResponse
type LdapSettingsResponse struct {
	Response *LdapSettings `json:"response,omitempty"`
}

// NewLdapSettingsResponse instantiates a new LdapSettingsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLdapSettingsResponse() *LdapSettingsResponse {
	this := LdapSettingsResponse{}
	return &this
}

// NewLdapSettingsResponseWithDefaults instantiates a new LdapSettingsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLdapSettingsResponseWithDefaults() *LdapSettingsResponse {
	this := LdapSettingsResponse{}
	return &this
}

// GetResponse returns the Response field value if set, zero value otherwise.
func (o *LdapSettingsResponse) GetResponse() LdapSettings {
	if o == nil || o.Response == nil {
		var ret LdapSettings
		return ret
	}
	return *o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LdapSettingsResponse) GetResponseOk() (*LdapSettings, bool) {
	if o == nil || o.Response == nil {
		return nil, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *LdapSettingsResponse) HasResponse() bool {
	if o != nil && o.Response != nil {
		return true
	}

	return false
}

// SetResponse gets a reference to the given LdapSettings and assigns it to the Response field.
func (o *LdapSettingsResponse) SetResponse(v LdapSettings) {
	o.Response = &v
}

func (o LdapSettingsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Response != nil {
		toSerialize["response"] = o.Response
	}
	return json.Marshal(toSerialize)
}

type NullableLdapSettingsResponse struct {
	value *LdapSettingsResponse
	isSet bool
}

func (v NullableLdapSettingsResponse) Get() *LdapSettingsResponse {
	return v.value
}

func (v *NullableLdapSettingsResponse) Set(val *LdapSettingsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableLdapSettingsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableLdapSettingsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLdapSettingsResponse(val *LdapSettingsResponse) *NullableLdapSettingsResponse {
	return &NullableLdapSettingsResponse{value: val, isSet: true}
}

func (v NullableLdapSettingsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLdapSettingsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


